version: '3.8'

services:
  backend:
    build: ./backend
    container_name: KIR-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env

  frontend:
    build: ./frontend
    container_name: KIR-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules